api:
  api:
    env:
      environment: develop
      modelWeightsPath: ../models/weights.pt
    image:
      repository: test-task-api
      tag: v0.1.0
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
