api:
  api:
    env:
      modelMetadataPath: ../models/metadata.json
      modelWeightsPath: ../models/weights.pt
    image:
      repository: test-task-api
      tag: v0.1.0
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  replicas: 1
  type: ClusterIP
cm0:
  metadataJson: '{"n_letters": 58, "n_hidden": 128, "n_categories": 18, "all_categories":
    ["Czech", "German", "Arabic", "Japanese", "Chinese", "Vietnamese", "Russian",
    "French", "Irish", "English", "Spanish", "Greek", "Italian", "Portuguese", "Scottish",
    "Dutch", "Korean", "Polish"]}'
kubernetesClusterDomain: cluster.local
