apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-chart.fullname" . }}-api
  labels:
    io.kompose.service: api
  {{- include "test-chart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
spec:
  type: {{ .Values.api.type }}
  selector:
    io.kompose.service: api
  {{- include "test-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 }}