apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - command:
            - uvicorn
            - main:app
            - --reload
            - --host
            - 0.0.0.0
            - --log-level
            - debug
          env:
            - name: MODEL_METADATA_PATH
              value: ../models/metadata.json
            - name: MODEL_WEIGHTS_PATH
              value: ../models/weights.pt
          image: test-task-api:v0.1.0
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/models
              name: api-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: api-cm0
          name: api-cm0
